---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: salt_solo
  require_chef: false
  formula: metricbeat
  state_top:
    base:
      '*':
        - metricbeat

platforms:
  - name: ubuntu-14.04

suites:
  - name: default

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=kitchen@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
