---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  require_chef: false
  formula: metricbeat
  state_top:
    base:
      '*':
        - metricbeat

platforms:
  - name: debian-jessie
    driver_config:
      run_command: /sbin/init

suites:
  - name: default
  - name: config-pillar-set
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - metricbeat
      pillars-from-files:
        metricbeat.sls: pillar.example

verifier:
  name: shell
  remote_exec: false
  command: testinfra -vvv --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$KITCHEN_SUITE
